### ISSUE TITLE
Multiple Labels

### ISSUE THREAD

**Issue by Reichenbachian** [jifalops/cypher-dto#20]
Is it currently possible to have multiple labels in a derived struct? Something like

```
#[derive(Debug, Clone, Deserialize, Serialize, Node, ToSchema)]
#[names("Person", "Investor")]
pub struct Person {
    #[id]
    pub name: String,
    pub description: String,
}
```

?

**Comment by Reichenbachian** [comment]
If not, I might implement something like this in my fork and you can copy over if you want.

**Comment by jifalops** [comment]
No not currently. There could be another attribute macro like in your example above. I'd be interested in that :)

**Comment by jifalops** [comment]
This is now in the main branch and should be released later today.

```rust
#[derive(Node)]
#[labels("Person", "Investor")]
pub struct Person {
    #[id]
    pub name: String,
    pub description: String,
}
```

The attribute only comes into scope for Nodes, but the associated getter function, `labels()` is on both Nodes and Relations. For relations it's always an array with one element, the relationship type.
